public enum ErrorCode {
    OK, INVALID_ARGUMENT_FORMAT, UNEXCEPTED_ARGUMENT,
    INVALID_ARGUMENT_NAME,
    MISSING_STRING,
    MISSING_INTEGER, INVALID_INTEGER,
    MISSING_DOUBLE, INVALID_DOUBLE
}
